# Generated by Django 3.2.11 on 2022-02-04 15:49

from django.conf import settings
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookclub', '0006_auto_20220201_2115'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='club',
            name='books',
        ),
        migrations.RemoveField(
            model_name='user',
            name='books',
        ),
        migrations.RemoveField(
            model_name='user',
            name='clubs',
        ),
        migrations.AddField(
            model_name='book',
            name='clubs',
            field=models.ManyToManyField(related_name='books', to='bookclub.Club'),
        ),
        migrations.AlterField(
            model_name='book',
            name='readers',
            field=models.ManyToManyField(related_name='books', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='club',
            name='members',
            field=models.ManyToManyField(related_name='clubs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='rating',
            name='rating',
            field=models.SmallIntegerField(validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(0)]),
        ),
    ]
